# Generated by Django 6.1.1 on 2026-09-10 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nacionalidad', models.CharField(blank=True, max_length=100)),
                ('biografia_breve', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('genero', models.CharField(blank=True, max_length=100)),
                ('estado_lectura', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('leido', 'Leído')], default='pendiente', max_length=20)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='libros.autor')),
            ],
        ),
    ]
